{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.name }}
  name: {{ .Values.serviceAccount.name }}
  {{- else }}
  name: {{ template "spinnaker.fullname" . }}-halyard
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
{{- end }}